theme: jekyll-theme-hacker
title: Jesse Portfolio
author: Jesse Richter
email: justjesserichter@gmail.com
description: A wonderful site
github_username:  jesserichter
#to create post in main directory do 2021-month-day-title.md no space
#to create tab in site do name_of_tab.md
